language: php

php:
  - 5.3
  - 5.4

before_script:
    - composer install
    - pyrus install pear/PHP_CodeSniffer
    - phpenv rehash

script:
    - phpunit
    - phpcs --ignore=vendor/* --standard=PSR2 -n --encoding=UTF-8 --report=summary ./
    